### ISSUE TITLE
MQTT No Ok esponse

### ISSUE THREAD

**Issue by mhanuel26** [ronpang/WizFi360-cpy#3]
Hi,

I am getting the following error while executing aio.py for single MQTT

```
%Run -c $EDITOR_CONTENT
ESP AT commands
---> AT+MQTTTOPIC="username/feeds/test","username/feeds/test"
<--- b'AT+MQTTTOPIC="username/feeds/test","username/feeds/test"\r\n\r\nOK\r\n'
---> AT+MQTTSET="username","aio_XXXXXXXXXXXXXXXXXXX","",60
<--- b'AT+MQTTSET="username","aio_XXXXXXXXXXXXXXXXXXX","",60\r\n\r\nOK\r\n'
---> AT+MQTTCON=0,"io.adafruit.com",1883
<--- b'AT+MQTTCON=0,"io.adafruit.com",1883\r\nno ip\r\n\r\nERROR\r\n'
---> AT+MQTTCON=0,"io.adafruit.com",1883
<--- b'AT+MQTTCON=0,"io.adafruit.com",1883\r\nno ip\r\n\r\nERROR\r\n'
---> AT+MQTTCON=0,"io.adafruit.com",1883
<--- b'AT+MQTTCON=0,"io.adafruit.com",1883\r\nno ip\r\n\r\nERROR\r\n'
Traceback (most recent call last):
  File "<stdin>", line 54, in <module>
  File "/lib/adafruit_espatcontrol/adafruit_espatcontrol_wifimanager.py", line 226, in IO_Con
  File "/lib/adafruit_espatcontrol/adafruit_espatcontrol.py", line 590, in at_response
OKError: No OK response to AT+MQTTCON=0,"io.adafruit.com",1883
```

I know the module can connect to the internet as I have run succesfully the HTTP example that post to the feed in adafruit, 

```
%Run -c $EDITOR_CONTENT
ESP AT commands
Posting data...b'CONNECT'
{'created_at': '2022-10-26T05:38:27Z', 'id': '0F52XZV9X445Q2CAWHC5X2HEQ2', 'expiration': '2022-11-25T06:38:27Z', 'created_epoch': 1666762707, 'feed_id': 2351232, 'value': '20', 'feed_key': 'temp-wizfi360'}
OK
Posting data...{'created_at': '2022-10-26T05:38:45Z', 'id': '0F52Y00S1GSBVHN9Z34D0DHDV1', 'expiration': '2022-11-25T06:38:45Z', 'created_epoch': 1666762725, 'feed_id': 2351232, 'value': '20', 'feed_key': 'temp-wizfi360'}
OK
```

And also the ping example (actually using io.adafruit.com) is working fine

```
%Run -c $EDITOR_CONTENT
ESP AT commands
Resetting ESP module
---> at
<--- b'at\r\n\r\nOK\r\n'
Scanning for AP's
---> AT
<--- b'AT\r\n\r\nOK\r\n'
---> ATE0
<--- b'ATE0\r\n\r\nOK\r\n'
Changing baudrate to: 115200
---> AT+UART_CUR=115200,8,1,0,2

---> AT
<--- b'\r\nOK\r\n'
---> AT+GMR
<--- b'AT version:1.1.1.7(May  4 2021 15:14:59)\r\nSDK version:3.2.0(a0ffff9f)\r\ncompile time:May  4 2021 15:14:59\r\n\r\nOK\r\n'
---> AT+CIPMUX?
<--- b'+CIPMUX:0\r\n\r\nOK\r\n'
---> AT+CIPSSLSIZE=4096
<--- b'\r\nOK\r\n'
---> AT+CWMODE?
<--- b'+CWMODE:1\r\n\r\nOK\r\n'
---> AT+CWLAP
<--- b'+CWLAP:(4,"TraceAP",-61,"28:11:a8:15:46:6d",1,0)\r\n+CWLAP:(4,"VODAFONE-DE00",-89,"48:3e:5e:52:de:01",2,1)\r\n+CWLAP:(4,"Vodafone-Guest",-89,"6a:3e:5e:52:de:04",2,0)\r\n+CWLAP:(3,"develwifi",-51,"28:87:ba:c9:e5:a6",4,1)\r\n+CWLAP:(3,"develwifi",-81,"28:87:ba:c9:e2:4a",4,1)\r\n+CWLAP:(4,"VODAFONE-FD60",-97,"74:9d:79:af:fd:61",5,1)\r\n+CWLAP:(3,"Linksys05947",-55,"94:10:3e:1d:c5:92",10,1)\r\n+CWLAP:(3,"SKYBLJXN",-85,"c0:a3:6e:e8:3d:4a",11,1)\r\n\r\nOK\r\n'
[4, 'TraceAP', -61, '28:11:a8:15:46:6d', 1, 0]
[4, 'VODAFONE-DE00', -89, '48:3e:5e:52:de:01', 2, 1]
[4, 'Vodafone-Guest', -89, '6a:3e:5e:52:de:04', 2, 0]
[3, 'develwifi', -51, '28:87:ba:c9:e5:a6', 4, 1]
[3, 'develwifi', -81, '28:87:ba:c9:e2:4a', 4, 1]
[4, 'VODAFONE-FD60', -97, '74:9d:79:af:fd:61', 5, 1]
[3, 'Linksys05947', -55, '94:10:3e:1d:c5:92', 10, 1]
[3, 'SKYBLJXN', -85, 'c0:a3:6e:e8:3d:4a', 11, 1]
Checking connection...
Connecting...
---> AT+CIPSTATUS
<--- b'STATUS:5\r\n\r\nOK\r\n'
Connected to None
---> AT+CWMODE?
<--- b'+CWMODE:1\r\n\r\nOK\r\n'
---> AT+CIPSTATUS
<--- b'STATUS:5\r\n\r\nOK\r\n'
---> AT+CWJAP="TraceAP","Liberty123"
<--- b'WIFI CONNECTED\r\nWIFI GOT IP\r\n'
---> AT+CIPSNTPCFG=1,-5
<--- b'\r\nOK\r\n'
---> AT+CIFSR
<--- b'+CIFSR:STAIP,"192.168.10.13"\r\n+CIFSR:STAMAC,"00:08:dc:6b:c0:9d"\r\n\r\nOK\r\n'
My IP Address: 192.168.10.13
Connected to AT software version  AT version:1.1.1.7(May  4 2021 15:14:59)
---> AT+CIFSR
<--- b'+CIFSR:STAIP,"192.168.10.13"\r\n+CIFSR:STAMAC,"00:08:dc:6b:c0:9d"\r\n\r\nOK\r\n'
IP address  192.168.10.13
Pinging io.adafruit.com...---> AT+PING="io.adafruit.com"
<--- b'+102\r\n\r\nOK\r\n'
102
Pinging io.adafruit.com...---> AT+PING="io.adafruit.com"
<--- b'+100\r\n\r\nOK\r\n'
100
Pinging io.adafruit.com...---> AT+PING="io.adafruit.com"
<--- b'+100\r\n\r\nOK\r\n'
100
```

**Comment by ronpang** [comment]
Hi @mhanuel26,

According to the information that you provided, it seems like the adafruit io has rejected from your connection.

I had tried this before during my testing due to frequently testing my codes. 

Therefore, I will suggest the following methods.

1. Upgrade your WizFi360 firmware version to 1.1.1.9. Since my library and codes has upgraded to work on 1.1.1.9 version, therefore please use my  [firmware Upgrade](https://github.com/ronpang/WizFi360-cpy/tree/main/examples/Firmware%20upgrade) code for testing.

2. If the problem is still occur, please disconnect your WizFi360-EVB-PICO for few minutes and retry.

If you have any further question, please feel free to let me know.

Thanks,
Ron

My testing result for comparision: 
```ESP AT commands
---> AT+MQTTTOPIC="ronpang/feeds/test","ronpang/feeds/test"
<--- b'AT+MQTTTOPIC="ronpang/feeds/test","ronpang/feeds/test"\r\n\r\nOK\r\n'
---> AT+MQTTSET="ronpang","XXXXXXXXXXXXXXXXXXXXXXXXX","",60
<--- b'AT+MQTTSET="ronpang","XXXXXXXXXXXXXXXXXXXXXXX","",60\r\n\r\nOK\r\n'
---> AT+MQTTCON=0,"io.adafruit.com",1883
<--- b'AT+MQTTCON=0,"io.adafruit.com",1883\r\nCONNECT\r\n\r\nOK\r\n'
b''
None None
---> AT+MQTTPUB="0"
<--- b'AT+MQTTPUB="0"\r\n\r\nOK\r\n'
b'ronpang/feeds/test -> 0\r\n'
test 0
---> AT+MQTTPUB="1"
<--- b'AT+MQTTPUB="1"\r\n\r\nOK\r\n'
b'ronpang/feeds/test -> 1\r\n'
test 1
---> AT+MQTTPUB="2"
<--- b'AT+MQTTPUB="2"\r\n\r\nOK\r\n'
b'ronpang/feeds/test -> 2\r\n'
test 2
---> AT+MQTTPUB="3"
<--- b'AT+MQTTPUB="3"\r\n\r\nOK\r\n'
b'ronpang/feeds/test -> 3\r\n'
test 3
---> AT+MQTTPUB="4"
<--- b'AT+MQTTPUB="4"\r\n\r\nOK\r\n'
b'ronpang/feeds/test -> 4\r\n'
test 4
---> AT+MQTTPUB="5"
<--- b'AT+MQTTPUB="5"\r\n\r\nOK\r\n'
---> AT+MQTTDIS
<--- b'AT+MQTTDIS\r\nCLOSED\r\n'```

**Comment by ronpang** [comment]
Hi @mhanuel26,

Since you have leak your adafruit io information on github, please remember to change your aio key before using the codes.

Thanks,
Ron

**Comment by mhanuel26** [comment]
Hi @ronpang ,

Thanks for your comments,

I have updated to version 1.1.1.9

`<--- b'AT version:1.1.1.9(Sep  5 2022 13:07:48)\r\nSDK version:3.2.0(a0ffff9f)\r\ncompile time:Sep  5 2022 13:07:48\r\n\r\nOK\r\n'`

But the problem persists

`<--- b'AT+MQTTCON=0,"io.adafruit.com",1883\r\nno ip\r\n\r\nERROR\r\n'`

Any other idea how to further debug the issue? 

I have a local mosquitto server here for tests as well, I have tried changing the address in adafruit_espatcontrol_wifimanager 

for instance replacing "io.adafruit.com" with my local ip address such as "192.168.10.254" but result is the same.

`<--- b'AT+MQTTCON=0,"192.168.10.254",1883\r\nno ip\r\n\r\nERROR\r\n'`

Comments will be appreciated.

**Comment by ronpang** [comment]
Hi @mhanuel26,

Please know that MQTT protocol that I made is currently for adafruit io only. 

I didn't test for other MQTT brokers. 

However, I will check on this "no ip" issue with our HQ members.

Thanks,
Ron

**Comment by ronpang** [comment]
Hi @mhanuel26,

Thank you for letting me know the error of my codes. :)

I had found the issue from the code is related to my codes didn't check the WizFi360 is it connected to a AP / router.

I had added checking the connection status to [IO_Con](https://github.com/ronpang/WizFi360-cpy/blob/main/lib/adafruit_espatcontrol/adafruit_espatcontrol_wifimanager.py#L209) for ensuring WizFi360 is connected to a router.

Added codes:
```python
        if not self._esp.is_connected: #check is the wizfi360 is connected to a router.
            self.connect()
```

I had tried the codes and it works fine. 
Please check the wifimanger.py to the latest one that I just uploaded to github.

1. I factory reset the module, it shows the same result as you do.
```
ESP AT commands
---> AT+RESTORE
<--- b'AT+RESTORE\r\n\r\nOK\r\n'
---> AT+MQTTTOPIC="ronpang/feeds/test","ronpang/feeds/test"
<--- b'\r\nready\r\n'
---> AT+MQTTTOPIC="ronpang/feeds/test","ronpang/feeds/test"
<--- b'AT+MQTTTOPIC="ronpang/feeds/test","ronpang/feeds/test"\r\n\r\nOK\r\n'
---> AT+MQTTSET="ronpang","XXXXXXXXXXXXXXXXX","",60
<--- b'AT+MQTTSET="ronpang","XXXXXXXXXXXXXXXXXXXX","",60\r\n\r\nOK\r\n'
---> AT+MQTTCON=0,"io.adafruit.com",1883
<--- b'AT+MQTTCON=0,"io.adafruit.com",1883\r\nno ip\r\n\r\nERROR\r\n'
---> AT+MQTTCON=0,"io.adafruit.com",1883
<--- b'AT+MQTTCON=0,"io.adafruit.com",1883\r\nno ip\r\n\r\nERROR\r\n'
---> AT+MQTTCON=0,"io.adafruit.com",1883
<--- b'AT+MQTTCON=0,"io.adafruit.com",1883\r\nno ip\r\n\r\nERROR\r\n'
```
2. After I added the connection status with AP, it shows the following result.
```
ESP AT commands
---> AT+RESTORE
<--- b'AT+RESTORE\r\n\r\nOK\r\n'
---> AT+MQTTTOPIC="ronpang/feeds/test","ronpang/feeds/test"
<--- b'\r\nready\r\n'
---> AT+MQTTTOPIC="ronpang/feeds/test","ronpang/feeds/test"
<--- b'AT+MQTTTOPIC="ronpang/feeds/test","ronpang/feeds/test"\r\n\r\nOK\r\n'
---> AT
<--- b'AT\r\n\r\nOK\r\n'
---> ATE0
<--- b'ATE0\r\n\r\nOK\r\n'
Changing baudrate to: 115200
---> AT+UART_CUR=115200,8,1,0,2

---> AT
<--- b'\r\nOK\r\n'
---> AT+GMR
<--- b'AT version:1.1.1.7(May  4 2021 15:14:59)\r\nSDK version:3.2.0(a0ffff9f)\r\ncompile time:May  4 2021 15:14:59\r\n\r\nOK\r\n'
---> AT+CIPMUX?
<--- b'+CIPMUX:0\r\n\r\nOK\r\n'
---> AT+CIPSSLSIZE=4096
<--- b'\r\nOK\r\n'
---> ATE0
<--- b'\r\nOK\r\n'
Changing baudrate to: 115200
---> AT+UART_CUR=115200,8,1,0,2

---> AT
<--- b'\r\nOK\r\n'
---> AT+CIPSTATUS
<--- b'STATUS:5\r\n\r\nOK\r\n'
---> ATE0
<--- b'\r\nOK\r\n'
Changing baudrate to: 115200
---> AT+UART_CUR=115200,8,1,0,2

---> AT
<--- b'\r\nOK\r\n'
---> AT+CIPSTATUS
<--- b'STATUS:5\r\n\r\nOK\r\n'
---> AT+CIPSTATUS
<--- b'STATUS:5\r\n\r\nOK\r\n'
Connected to None
---> AT+CWMODE?
<--- b'+CWMODE:1\r\n\r\nOK\r\n'
---> AT+CIPSTATUS
<--- b'STATUS:5\r\n\r\nOK\r\n'
---> AT+CWJAP="wiznet","XXXXXXXXX"
<--- b'WIFI CONNECTED\r\nWIFI GOT IP\r\n'
---> AT+CIFSR
<--- b'+CIFSR:STAIP,"10.0.1.132"\r\n+CIFSR:STAMAC,"00:08:dc:69:e1:a7"\r\n\r\nOK\r\n'
My IP Address: 10.0.1.132
---> ATE0
<--- b'\r\nOK\r\n'
Changing baudrate to: 115200
---> AT+UART_CUR=115200,8,1,0,2

---> AT
<--- b'\r\nOK\r\n'
---> AT+CIPSTATUS
<--- b'STATUS:2\r\n\r\nOK\r\n'
---> AT+MQTTSET="ronpang","XXXXXXXXXXXXXXXXXXXX","",60
<--- b'\r\nOK\r\n'
---> AT+MQTTCON=0,"io.adafruit.com",1883
<--- b'CONNECT\r\n\r\nOK\r\n'
b''
None None
---> AT+MQTTPUB="0"
<--- b'\r\nOK\r\n'
b'ronpang/feeds/test -> 0\r\n'
test 0
---> AT+MQTTPUB="1"
<--- b'\r\nOK\r\n'
b'ronpang/feeds/test -> 1\r\n'
test 1
---> AT+MQTTPUB="2"
<--- b'\r\nOK\r\n'
b'ronpang/feeds/test -> 2\r\n'
test 2
---> AT+MQTTPUB="3"
<--- b'\r\nOK\r\n'
b'ronpang/feeds/test -> 3\r\n'
test 3
---> AT+MQTTPUB="4"
<--- b'\r\nOK\r\n'
b'ronpang/feeds/test -> 4\r\n'
test 4
---> AT+MQTTPUB="5"
<--- b'\r\nOK\r\n'
---> AT+MQTTDIS
<--- b'CLOSED\r\n'
```


Thanks,
Ron

**Comment by mhanuel26** [comment]
Hi @ronpang ,

That certainly works for me too. 

What changes do you think might be needed for making this work with another broker like mosquitto?

I will investigate the code but it might worth to get your comments as to where I can start looking at. 

The other question is if you have a TCP server example by chance.

Thanks a lot,
Manuel

**Comment by ronpang** [comment]
@mhanuel26,

I had added some new codes and modified the secret.py and adafruit_espatcontrol_wifimanager.py

Secret.py:  
1. adafruitio user name could use as mqtt broker's username
2. adafruitio key could use as mqtt broker's password
3. I added client id (if the broker requires)
4. For my testing methods and secrect setup, please refer to the setups for our [WizFi360 MQTT demo](https://youtu.be/5TEvKznndKY)

adafruit_espatcontrol_wifimanager.py:
1. IO_Con: Added ip parameter - type your broker's IP address will be fine
2. IO_topics : it could use for normal topics
3. clean_data: it could collect simple feedback inforamtion from subscribed topics.

Example: 
[MQTT](https://github.com/ronpang/WizFi360-cpy/tree/main/examples/MQTT)

For the TCP example, I will try to add it within today. 
If I didn't upload anything, you may need to wait until next week. 

Thanks,
Ron

**Comment by mhanuel26** [comment]
Hi @ronpang ,

I tested the MQTT with a local mostitto server and it works.

Thanks a lot for your help,
Manuel
